# [.github/workflows/Documentation.yml]
name: Documentation

on:
  push:
    branches:
      - main
      - dev
    tags: '*'
  pull_request:

jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v6 # v6
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v3
        with:
          version: 1
      - name: Cache
        uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1 
      - uses: julia-actions/julia-docdeploy@v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # when run by tagbot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_DEBUG: true
